Contrail311 fixes
salt-formulas/salt-formula-opencontrail pull request #7
Opened 2017-03-07 00:03 UTC by pjediny

- WebUI cassandra port parameterization, so we can use 9042 for new installation and 9160 for old ones.
- According to https://github.com/Juniper/contrail-controller/wiki/RBAC we should use aaa_mode = no-auth so we can use WebUI

2017-03-07 09:37 UTC, cznewt commented on metadata/service/control/cluster.yml
> +        cassandra_port: ${_param:opencontrail_webui_cassandra_port}
split this to engine, host, port

2017-03-07 09:37 UTC, cznewt commented on opencontrail/files/3.0/config.global.js
> +config.cassandra.server_port = '{{ web.database.cassandra_port }}';
and web.database.port here

2017-03-07 09:37 UTC, cznewt commented on opencontrail/files/3.0/contrail-analytics-api.conf
> +aaa_mode = {{ collector.api.get('aaa_mode', 'no-auth') }}
dependent on version?

2017-03-07 10:02 UTC, pjediny commented on opencontrail/files/3.0/contrail-analytics-api.conf
> +aaa_mode = {{ collector.api.get('aaa_mode', 'no-auth') }}
This is for @pupapaik to decide, he has access to contrail 3.0.x to test it. This renders only for version 3, so it should not break version 2.

2017-03-07 10:03 UTC, pjediny commented
Amended changes proposed by @cznewt

2017-03-08 12:10 UTC, pupapaik requested changes

2017-03-08 12:10 UTC, pupapaik commented on opencontrail/files/3.0/contrail-analytics-api.conf
> +aaa_mode = {{ collector.api.get('aaa_mode', 'no-auth') }}
remove api section - collector.get('aaa_mode', 'no-auth')

2017-03-08 12:10 UTC, pupapaik commented on metadata/service/control/analytics.yml
> +      api:
remove section

2017-03-08 12:10 UTC, pupapaik commented on metadata/service/control/analytics.yml
> +        aaa_mode: ${_param:opencontrail_api_aaa_mode}
put value aaa_mode: no-auth

2017-03-08 12:33 UTC, pupapaik requested changes

2017-03-08 12:33 UTC, pupapaik commented on metadata/service/control/cluster.yml
> +    opencontrail_web_database_port: 9160
remove

2017-03-08 12:33 UTC, pupapaik commented on metadata/service/control/cluster.yml
> +        port: ${_param:opencontrail_web_database_port}
9160

2017-03-08 12:33 UTC, pupapaik commented on metadata/service/control/control.yml
> +        port: ${_param:opencontrail_web_database_port}
9160

2017-03-08 12:33 UTC, pupapaik commented on metadata/service/control/single.yml
> +    opencontrail_web_database_port: 9160
remove

2017-03-08 12:33 UTC, pupapaik commented on metadata/service/control/single.yml
> +        port: ${_param:opencontrail_web_database_port}
9160

2017-03-08 12:56 UTC, merged